# Generated by Django 3.1.4 on 2020-12-10 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('picture', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PotentialMatchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfect_match', models.BooleanField(default=False)),
                ('manually_eliminated', models.BooleanField(default=False)),
                ('eliminated_via_truthbooth', models.BooleanField(default=False)),
                ('eliminated_via_blackout', models.BooleanField(default=False)),
                ('participant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_matchup_participant1', to='ayto.participant')),
                ('participant2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_matchup_participant2', to='ayto.participant')),
            ],
            options={
                'unique_together': {('participant1', 'participant2')},
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('matches_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TruthBooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfect_match', models.BooleanField(default=False)),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayto.potentialmatchup')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayto.week')),
            ],
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayto.potentialmatchup')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayto.week')),
            ],
            options={
                'unique_together': {('week', 'matchup')},
            },
        ),
    ]
