# Generated by Django 3.1.4 on 2020-12-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayto', '0002_participant_url_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='url_slug',
            field=models.CharField(default='asdf', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
