# Generated by Django 3.1.4 on 2020-12-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayto', '0004_potentialmatchup_speculative_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialmatchup',
            name='perfect_match_via_truthbooth',
            field=models.BooleanField(default=False),
        ),
    ]
